[tools]
terraform = "1.14.3"
node = "24.0"
python = "3.14.2"
trivy = "0.68.2"

[env]
# Autoconfigure venv
_.python.venv = { path = ".venv", create = true }

[tasks]
install_deps = "uv pip install pre-commit"
